### ISSUE TITLE
Which is the correct lang file?

### ISSUE THREAD

**Issue by creeper-0910** [misaka10843/ShinColle#19]
I noticed that the Japanese lang file is out of date and tried to fix it.
However, I am very confused because there are entries in "en_us.lang" and "zh_cn.lang" that do not exist in each other (e.g. item.shincolle:shipegg74.name).
Which is the correct lang file?

**Comment by misaka10843** [comment]
The zh_cn file is the correct one, but the other language files are not modified due to maintenance issues qwq

**Comment by creeper-0910** [comment]
Thank you! I will correct the Japanese translation later!
