### ISSUE TITLE
[feature]如何方便的跨世界传送舰娘？

### ISSUE THREAD

**Issue by redXpanda** [misaka10843/ShinColle#21]
玩家需要带着舰队跨越各个维度，希望舰队能跟着自己传送。
如果做起来麻烦的话，新增一个道具用于把舰娘收进背包（或者某个道具中），然后自由放出，也可以。

**Comment by misaka10843** [comment]
对不起这么晚才回复，因为本mod的代码可以算是非常复杂，而且添加新的功能的话还停留在1.12.2有点得不偿失了，所以可能不会考虑添加新的功能
更多内容可以查看
#22
