### ISSUE TITLE
抽水功能异常

### ISSUE THREAD

**Issue by ZD54** [misaka10843/ShinColle#24]
### 🐛 描述(Description)

能看见水消失，但在机娘背包里的存储设备存储量为0.

### 📷 复现步骤(Steps to Reproduce)

1.在补给舰发现问题
2.在潜艇U511重现                  
3.

### 版本(version)

ShinColle-1.12.2.1.3-N

### 系统(OS)

Windows10~+

### 是否确认在单独环境下也有此问题？

- [X] 我非常确认在单独环境下也有此问题

### 是否确认在降级之后问题消失？

- [ ] 我非常确认在降级之后问题消失

###  🖼 截图(Screenshots)

![Minecraft 1 12 2 2024_10_22 1_46_22](https://github.com/user-attachments/assets/57678963-764b-42f8-bcf4-08498ff84c12)
![Minecraft 1 12 2 2024_10_22 1_39_01](https://github.com/user-attachments/assets/435283d4-9cf7-4902-bd89-8a730b7d28c8)
![Minecraft 1 12 2 2024_10_22 1_39_01](https://github.com/user-attachments/assets/abc42305-22ce-4071-87af-e890c2eca0da)
![Minecraft 1 12 2 2024_10_22 1_46_22](https://github.com/user-attachments/assets/02b6ac50-45ae-4d94-96a2-63409d14ea95)

**Comment by misaka10843** [comment]
关于这个功能的话推测是因为此功能根本没有制作（ship_tank 为液体槽的ID，但是搜索只能查找到合成表中有ID）
https://github.com/misaka10843/ShinColle/blob/8cd4013e984c201a951020993af5fb555f7dcd6a/src/main/java/com/lulan/shincolle/init/ModRecipes.java#L225-L228
建议还是不要使用此功能x

**Comment by ZD54** [comment]
这MOD好玩就是作者弃坑是真的难受
